name: loja_virtual
description: A new Flutter project.
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^5.0.0
  cloud_firestore: ^3.4.8
  firebase_auth: ^3.9.0
  firebase_storage: ^10.3.8
  firebase_core: ^1.22.0
  carousel_slider: ^4.1.1
  flutter_staggered_grid_view: ^0.6.2
  transparent_image: ^1.0.0
  alphabet_list_scroll_view: ^1.0.6
  faker: ^1.2.1
  image_picker: ^0.8.6
  image_cropper: ^3.0.1
  uuid: ^3.0.4
  dio: ^4.0.6
  brasil_fields: ^1.0.0
  geolocator: ^9.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
