name: loja_virtual
description: A new Flutter project.
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^5.0.0
  cloud_firestore: ^3.4.8
  firebase_auth: ^3.9.0
  firebase_storage: ^10.3.8
  firebase_core: ^1.22.0
  carousel_slider: ^4.1.1
  flutter_staggered_grid_view: ^0.6.2
  transparent_image: ^1.0.0
  alphabet_list_scroll_view: ^1.0.6
  faker: ^1.2.1
  image_picker: ^0.8.6
  image_cropper: ^3.0.1
  uuid: ^3.0.4
  dio: ^4.0.6
  brasil_fields: ^1.0.0
  geolocator: ^9.0.2
  sliding_up_panel: ^2.0.0+1
  screenshot: ^1.3.0
  gallery_saver: ^2.3.2
  flutter_signin_button: ^2.0.0
  flip_card: ^0.7.0
  mask_text_input_formatter: ^2.4.0
  credit_card_type_detector: ^2.0.0
  cloud_functions: ^3.3.9
  cpf_cnpj_validator: ^2.0.0
  flutter_credit_card_detector: ^2.0.0
  firebase_messaging: ^13.1.0
  flutter_launcher_icons: ^0.12.0

flutter_icons:
  image_path: "assets/app/logo.png"
  android: "launcher_icon"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/app/logo.png"
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
